apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-5
  creationTimestamp: null
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-5
  template:
    metadata:
      labels:
        app: be-5
    spec:
      containers:
      - name: be-5
        image: 172.20.83.35:5000/5:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always
