apiVersion: v1
kind: Service
metadata:
  name: be-5
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodeport: 30005
 selector:
  app: be-5
 type: NodePort
status:
 loadBalancer: {}
