<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIhuuf0o\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIhuuf0o/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIhuuf0o.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIhuuf0o\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIhuuf0o\appProdProjectContainer([
    'container.build_hash' => 'Ihuuf0o',
    'container.build_id' => '1258f5ec',
    'container.build_time' => 1611512787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIhuuf0o');
